const products = [
    { id: 1, name: "Apple", category: "Fruits", price: 0.5, quantity: 10, unit: "kg" },
    { id: 2, name: "Milk", category: "Dairy", price: 1.2, quantity: 2, unit: "liters" },
    { id: 3, name: "Bread", category: "Bakery", price: 2.0, quantity: 1, unit: "loaf" },
    { id: 4, name: "Eggs", category: "Dairy", price: 3.5, quantity: 12, unit: "pieces" },
    { id: 5, name: "Carrots", category: "Vegetables", price: 1.0, quantity: 5, unit: "kg" },
    { id: 6, name: "Chicken Breast", category: "Meat", price: 5.0, quantity: 1, unit: "kg" },
    { id: 7, name: "Rice", category: "Grains", price: 2.5, quantity: 1, unit: "kg" },
    { id: 8, name: "Tomatoes", category: "Vegetables", price: 1.5, quantity: 2, unit: "kg" },
    { id: 9, name: "Cheese", category: "Dairy", price: 4.0, quantity: 0.5, unit: "kg" },
    { id: 10, name: "Orange Juice", category: "Beverages", price: 3.0, quantity: 1, unit: "liter" },
    { id: 11, name: "Banana", category: "Fruits", price: 0.3, quantity: 12, unit: "kg" },
    { id: 12, name: "Yogurt", category: "Dairy", price: 1.5, quantity: 1, unit: "kg" },
    { id: 13, name: "Croissant", category: "Bakery", price: 0.8, quantity: 6, unit: "pieces" },
    { id: 14, name: "Beef Steak", category: "Meat", price: 10.0, quantity: 1, unit: "kg" },
    { id: 15, name: "Potatoes", category: "Vegetables", price: 0.6, quantity: 5, unit: "kg" },
    { id: 16, name: "Pasta", category: "Grains", price: 1.8, quantity: 1, unit: "kg" },
    { id: 17, name: "Lettuce", category: "Vegetables", price: 0.5, quantity: 1, unit: "kg" },
    { id: 18, name: "Salmon", category: "Fish", price: 12.0, quantity: 1, unit: "kg" },
    { id: 19, name: "Almonds", category: "Nuts", price: 15.0, quantity: 0.5, unit: "kg" },
    { id: 20, name: "Orange", category: "Fruits", price: 0.4, quantity: 10, unit: "kg" },
    { id: 21, name: "Honey", category: "Condiments", price: 8.0, quantity: 0.5, unit: "kg" },
    { id: 22, name: "Peanut Butter", category: "Condiments", price: 3.0, quantity: 0.5, unit: "kg" },
    { id: 23, name: "Soy Sauce", category: "Condiments", price: 2.0, quantity: 1, unit: "liters" },
    { id: 24, name: "Olive Oil", category: "Condiments", price: 6.0, quantity: 0.5, unit: "liters" },
    { id: 25, name: "Frozen Pizza", category: "Frozen", price: 4.0, quantity: 1, unit: "pieces" },
    { id: 26, name: "Ice Cream", category: "Frozen", price: 5.0, quantity: 1, unit: "liter" },
    { id: 27, name: "Frozen Vegetables", category: "Frozen", price: 3.0, quantity: 1, unit: "kg" },
    { id: 28, name: "Tea", category: "Beverages", price: 2.0, quantity: 100, unit: "bags" },
    { id: 29, name: "Coffee", category: "Beverages", price: 10.0, quantity: 0.5, unit: "kg" },
    { id: 30, name: "Soda", category: "Beverages", price: 1.5, quantity: 1, unit: "liter" },
    { id: 31, name: "Cereal", category: "Grains", price: 3.0, quantity: 1, unit: "kg" },
    { id: 32, name: "Chips", category: "Snacks", price: 2.0, quantity: 200, unit: "grams" },
    { id: 33, name: "Chocolate", category: "Snacks", price: 1.5, quantity: 100, unit: "grams" },
    { id: 34, name: "Granola Bars", category: "Snacks", price: 4.0, quantity: 5, unit: "pieces" },
    { id: 35, name: "Tortilla Chips", category: "Snacks", price: 2.5, quantity: 200, unit: "grams" },
    // New products (total 100)
    { id: 36, name: "Avocado", category: "Fruits", price: 1.2, quantity: 6, unit: "pieces" },
    { id: 37, name: "Strawberries", category: "Fruits", price: 3.0, quantity: 1, unit: "kg" },
    { id: 38, name: "Cheddar Cheese", category: "Dairy", price: 5.0, quantity: 0.5, unit: "kg" },
    { id: 39, name: "Butter", category: "Dairy", price: 4.5, quantity: 0.5, unit: "kg" },
    { id: 40, name: "Whole Wheat Bread", category: "Bakery", price: 2.5, quantity: 1, unit: "loaf" },
    { id: 41, name: "Bagels", category: "Bakery", price: 1.8, quantity: 6, unit: "pieces" },
    { id: 42, name: "Lamb Chops", category: "Meat", price: 15.0, quantity: 1, unit: "kg" },
    { id: 43, name: "Pork Ribs", category: "Meat", price: 12.5, quantity: 1, unit: "kg" },
    { id: 44, name: "Sweet Potatoes", category: "Vegetables", price: 1.3, quantity: 5, unit: "kg" },
    { id: 45, name: "Zucchini", category: "Vegetables", price: 1.0, quantity: 3, unit: "kg" },
    { id: 46, name: "Spinach", category: "Vegetables", price: 2.0, quantity: 1, unit: "kg" },
    { id: 47, name: "Wheat Flour", category: "Grains", price: 1.2, quantity: 2, unit: "kg" },
    { id: 48, name: "Quinoa", category: "Grains", price: 4.0, quantity: 1, unit: "kg" },
    { id: 49, name: "Mushrooms", category: "Vegetables", price: 2.5, quantity: 1, unit: "kg" },
    { id: 50, name: "Tuna", category: "Fish", price: 8.0, quantity: 1, unit: "kg" },
    { id: 51, name: "Shrimp", category: "Fish", price: 14.0, quantity: 1, unit: "kg" },
    { id: 52, name: "Cashews", category: "Nuts", price: 16.0, quantity: 0.5, unit: "kg" },
    { id: 53, name: "Peanuts", category: "Nuts", price: 3.0, quantity: 0.5, unit: "kg" },
    { id: 54, name: "Grapes", category: "Fruits", price: 2.5, quantity: 5, unit: "kg" },
    { id: 55, name: "Kiwi", category: "Fruits", price: 3.5, quantity: 10, unit: "pieces" },
    { id: 56, name: "Coconut", category: "Fruits", price: 2.0, quantity: 1, unit: "piece" },
    { id: 57, name: "Ice Cream Cones", category: "Frozen", price: 4.0, quantity: 10, unit: "pieces" },
    { id: 58, name: "Frozen Chicken Wings", category: "Frozen", price: 8.0, quantity: 1, unit: "kg" },
    { id: 59, name: "Frozen Broccoli", category: "Frozen", price: 3.0, quantity: 1, unit: "kg" },
    { id: 60, name: "Frozen Berries", category: "Frozen", price: 5.0, quantity: 1, unit: "kg" },
    { id: 61, name: "Ice Cream Sandwiches", category: "Frozen", price: 6.0, quantity: 4, unit: "pieces" },
    { id: 62, name: "Herbal Tea", category: "Beverages", price: 3.0, quantity: 100, unit: "bags" },
    { id: 63, name: "Sports Drink", category: "Beverages", price: 1.8, quantity: 1, unit: "liter" },
    { id: 64, name: "Energy Drink", category: "Beverages", price: 2.5, quantity: 1, unit: "liter" },
    { id: 65, name: "Red Wine", category: "Beverages", price: 10.0, quantity: 0.75, unit: "liters" },
    { id: 66, name: "White Wine", category: "Beverages", price: 10.0, quantity: 0.75, unit: "liters" },
    { id: 67, name: "Sparkling Water", category: "Beverages", price: 1.0, quantity: 1, unit: "liter" },
    { id: 68, name: "Muesli", category: "Grains", price: 3.0, quantity: 1, unit: "kg" },
    { id: 69, name: "Rice Cakes", category: "Snacks", price: 2.0, quantity: 100, unit: "grams" },
    { id: 70, name: "Trail Mix", category: "Snacks", price: 5.0, quantity: 500, unit: "grams" },
    { id: 71, name: "Popcorn", category: "Snacks", price: 2.0, quantity: 200, unit: "grams" },
    { id: 72, name: "Fruit Snacks", category: "Snacks", price: 3.5, quantity: 10, unit: "pieces" },
    { id: 73, name: "Lemon", category: "Fruits", price: 0.3, quantity: 10, unit: "pieces" },
    { id: 74, name: "Pineapple", category: "Fruits", price: 2.0, quantity: 1, unit: "piece" },
    { id: 75, name: "Cabbage", category: "Vegetables", price: 0.4, quantity: 2, unit: "kg" },
    { id: 76, name: "Cauliflower", category: "Vegetables", price: 1.5, quantity: 1, unit: "kg" },
    { id: 77, name: "Bell Peppers", category: "Vegetables", price: 1.0, quantity: 1, unit: "kg" },
    { id: 78, name: "Chili Peppers", category: "Vegetables", price: 2.0, quantity: 0.5, unit: "kg" },
    { id: 79, name: "Garlic", category: "Vegetables", price: 0.5, quantity: 1, unit: "kg" },
    { id: 80, name: "Onions", category: "Vegetables", price: 0.6, quantity: 3, unit: "kg" },
    { id: 81, name: "Black Beans", category: "Canned", price: 1.0, quantity: 400, unit: "grams" },
    { id: 82, name: "Chickpeas", category: "Canned", price: 1.0, quantity: 400, unit: "grams" },
    { id: 83, name: "Tomato Sauce", category: "Canned", price: 1.5, quantity: 400, unit: "grams" },
    { id: 84, name: "Tuna in Oil", category: "Canned", price: 2.0, quantity: 160, unit: "grams" },
    { id: 85, name: "Peas", category: "Canned", price: 1.0, quantity: 400, unit: "grams" },
    { id: 86, name: "Pizza Sauce", category: "Canned", price: 2.0, quantity: 500, unit: "grams" },
    { id: 87, name: "Balsamic Vinegar", category: "Condiments", price: 3.5, quantity: 0.5, unit: "liters" },
    { id: 88, name: "Ketchup", category: "Condiments", price: 2.5, quantity: 0.5, unit: "liters" },
    { id: 89, name: "Mustard", category: "Condiments", price: 1.0, quantity: 0.5, unit: "liters" },
    { id: 90, name: "Barbecue Sauce", category: "Condiments", price: 2.5, quantity: 0.5, unit: "liters" },
    { id: 91, name: "Sriracha", category: "Condiments", price: 3.0, quantity: 0.5, unit: "liters" },
    { id: 92, name: "Ginger", category: "Spices", price: 2.0, quantity: 0.5, unit: "kg" },
    { id: 93, name: "Cinnamon", category: "Spices", price: 1.5, quantity: 0.5, unit: "kg" },
    { id: 94, name: "Cumin", category: "Spices", price: 1.5, quantity: 0.5, unit: "kg" },
    { id: 95, name: "Paprika", category: "Spices", price: 2.0, quantity: 0.5, unit: "kg" },
    { id: 96, name: "Black Pepper", category: "Spices", price: 1.5, quantity: 0.5, unit: "kg" },
    { id: 97, name: "Thyme", category: "Herbs", price: 2.5, quantity: 0.5, unit: "kg" },
    { id: 98, name: "Rosemary", category: "Herbs", price: 2.5, quantity: 0.5, unit: "kg" },
    { id: 99, name: "Parsley", category: "Herbs", price: 2.0, quantity: 0.5, unit: "kg" },
    { id: 100, name: "Basil", category: "Herbs", price: 2.0, quantity: 0.5, unit: "kg" },
  ];
  


  
  const getproductsbycategories = (catname) => {
    if (catname === "*") {
        return products;}
    return products.filter(x => x.category === catname);
  };
  
  const getAllCategories = () => {
    return Array.from(new Set(products.map(prod => prod.category)));
  };
  
  export { getproductsbycategories, getAllCategories };
  